version: "{branch}-{build}"
environment:
  global:
    PATCH_VER: 22
    HG_REV: 15326b4db607
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
install:
  - ps: dir 'c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc'
  - ps: dir 'c:\program files (x86)\microsoft visual studio\2017\community\vc\redist\msvc'
build_script:
- ps: >-
    $env:JAVA_HOME = "C:\Program Files\Java\jdk10"

    Invoke-WebRequest 'https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.9-bin.zip' -OutFile 'ant-bin.zip'

    Expand-Archive 'ant-bin.zip' -DestinationPath 'C:\ant'

    $env:PATH = ('C:\ant\apache-ant-1.9.9\bin;' + $env:Path)

    Invoke-WebRequest ("http://hg.openjdk.java.net/openjfx/jfx/rt/archive/" + $env:HG_REV + ".zip") -OutFile ($env:HG_REV + ".zip")

    Expand-Archive ($env:HG_REV + ".zip")

    cd ($env:HG_REV + "\rt-" + $env:HG_REV)

    (Get-Content build.gradle) | Foreach-Object {$_ -replace '^ext.OS_ARCH =.+$', 'ext.OS_ARCH = "x86"'} | Set-Content build.gradle

    (Get-Content buildSrc/win.gradle) | Foreach-Object {$_ -replace 'Professional', 'Community'} | Set-Content buildSrc/win.gradle

    (Get-Content buildSrc/genVSproperties.bat) | Foreach-Object {$_ -replace 'Professional', 'Community'} | Set-Content buildSrc/genVSproperties.bat

    (Get-Content modules/javafx.graphics/src/main/native-prism/PrismPrint.c) | Foreach-Object {$_ -replace 'JNIEXPORT jobject', 'JNIEXPORT jobject JNICALL'} | Set-Content modules/javafx.graphics/src/main/native-prism/PrismPrint.c

    $env:MSVC_VER = '14.14.26428'

    $env:MSVC_REDIST_VER = '14.14.26405'

    ./gradlew zips

    if ($LastExitCode -eq 0) {
      $host.SetShouldExit(0)
    }
- cmd: C:\cygwin64\bin\bash -e -l -c "cd ${HG_REV}/rt-${HG_REV}/build && zip -r sdk.zip sdk"
test: off
artifacts:
- path: ${HG_REV}/rt-${HG_REV}/build/sdk.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 9vEYpyGo8MTutVQyQTMECylYj87OoVNDLt0Jd7KuJK4DbyKs2VrGmVARDxLv6uR0
  artifact: /.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true
