version: "{branch}-{build}"
environment:
  global:
    PATCH_VER: 22
    HG_REV: 15326b4db607
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
build_script:
- ps: >-
    $Env:JAVA_HOME = "C:\Program Files\Java\jdk10"

    Invoke-WebRequest ("http://hg.openjdk.java.net/openjfx/jfx/rt/archive/" + $env:HG_REV + ".zip") -OutFile ($env:HG_REV + ".zip")

    dir

    Expand-Archive ($env:HG_REV + ".zip")

    cd ($env:HG_REV + "\rt-" + $env:HG_REV)

    ./gradlew sdkWin
test: off
artifacts:
- path: build/artifacts/bundles/*.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 9vEYpyGo8MTutVQyQTMECylYj87OoVNDLt0Jd7KuJK4DbyKs2VrGmVARDxLv6uR0
  artifact: /.*\.zip/
  on:
    branch: master
    appveyor_repo_tag: true
